- .vscode/cSpell.json
- docs/dev_setup.md
- src/setup.py
- src/sfctl/custom_app.py
This change moves to use a single requests session for the `application upload` command. This requires less setup and teardown than invoking each request as a new session. This improves the performance of the command.
> Fixing app upload to use a single session

- src/setup.py
- src/sfctl/custom_app.py
OpenSSL expects passwords to always be byte arrays, but in py3 they would be returned as unicode objects. This change fixes that behaviour.
> Fixing `application upload` to handle string encoding

- .travis.yml
- src/README.rst
- src/setup.py
Updating the Service Fabric SDK to the latest 6.0 version, this change includes:
- Changing to test RC1 package from custom source (not official SDK)
- Fixing `requests` package to lower version to fix conflict with `msrest` package
- Incrementing release to 1.2.0rc1
> Updating Service Fabric SDK to 6.0 release candidate

- src/README.rst
- src/sfctl/commands.py
- src/sfctl/params.py
This fixes several commands where parameters were being treated as strings instead of numbers. Also fixes a previous typo in a command name.
> Fix parameter parsing for numbers

- src/README.rst
- src/setup.py
- src/sfctl/custom_app.py
This fix introduces a few changes:
- `application upload` no longer uses a custom iterator. This change fixes connection resets and improves performance, fixes #15 
- Adds some stricter versioning around required packages
- Removes custom monkey patching and need to use pyopenssl
> Fixing application upload iterator and setting strict package version

- src/sfctl/custom_cluster.py
Clarified that certificate references in "cluster select" commands should be absolute.
> Clarification in cluster select help text

- src/README.rst
- src/sfctl/params.py
Fix load metrics parsing during `service update` by correctly parsing JSON encoded string. Fixes #46.
> Fixing load metric parsing

- requirements.txt
- src/README.rst
- src/setup.py
- src/sfctl/commands.py
- src/sfctl/helps/main.py
- src/sfctl/params.py
- src/sfctl/tests/live_scenario_test.py
- src/sfctl/tests/scenario_test.py
This PR updates the azure-servicefabric Python SDK to v6.0.2 and exposes a subset of the [Property Management APIs](https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-index-property-management) via standard commands.
I've only added commands relevant to modifying properties for existing Service Fabric names i.e. 'GettingStartedApplication/WebService' rather than the full name/property API surface. This works for our use case (adding app/service metadata) but appreciate you may want the commands to map to a more generalised API surface. 
Example usage can be seen below:
> Updated Python SDK version and added property management commands

- pylintrc
- src/README.rst
- src/setup.py
- src/sfctl/commands.py
- src/sfctl/custom_app.py
- src/sfctl/custom_app_type.py
- src/sfctl/custom_cluster.py
- src/sfctl/custom_cluster_upgrade.py
- src/sfctl/custom_compose.py
- src/sfctl/custom_health.py
- src/sfctl/custom_service.py
- src/sfctl/helps/app_type.py
- src/sfctl/helps/main.py
- src/sfctl/params.py
- src/sfctl/tests/app_test.py
- src/sfctl/tests/cluster_test.py
- src/sfctl/tests/service_test.py
- Updating to 6.1 Service Fabric runtime SDK
- Forcing adal to be a required dependency
Verifed:
> Updating to 6.1 SF Runtime

- requirements.txt
- src/README.rst
- src/setup.py
- src/sfctl/params.py
- src/sfctl/tests/command_processing_test.py
- src/sfctl/tests/correct_json.txt
- src/sfctl/tests/help_text_test.py
- src/sfctl/tests/incorrect_json.txt
- src/sfctl/tests/request_generation_test.py
- Give users the option of passing in a .txt file where they have to pass in a json value for an argument.
Verifed:
> Add support for passing json values to arguments as .txt files

- src/README.rst
- src/setup.py
- src/sfctl/params.py
- src/sfctl/tests/request_generation_test.py
- src/sfctl/tests/version_test.py
- Update release notes and versions for 6.0.0 release.
- Add parameter to set max results for query "sfctl node list"
Verifed:
> Update versions for 6.0.0 release and update get nodes query

- src/sfctl/custom_cluster.py
- src/sfctl/custom_service.py
- src/sfctl/helps/app.py
- src/sfctl/helps/container.py
- src/sfctl/helps/infrastructure.py
- src/sfctl/helps/main.py
- Add some fixes to the documentation. This includes a typo in the main help text about which version this release (6.0.0) should target.
Verifed:
> Help text update

- src/README.rst
- src/sfctl/custom_health.py
Fixes # .
- Allow reporting on "Error" state for report health on entities
Verified:
> Fix missing enum value in report health

- src/sfctl/custom_cluster.py
- src/sfctl/tests/cluster_test.py
Fixes PR #123 .
- Fix a typo
- Fix a test that was not correctly catching the typo because it wasn't correctly checking the return value.
Verified:
> Fix test issue where the correct issue is not being verified for

- src/setup.py
- src/sfctl/entry.py
- src/sfctl/send_telemetry_background.py
- src/sfctl/state.py
- src/sfctl/telemetry.py
Improve upon #152 to make telemetry send batched telemetry in order to improve performance.
Telemetry will write to a file and hold on to telemetry to send in chunks. Current value is 50 items per batch. There are limited retries, so that if there is something such as no internet connection, we retry intermittently. 
Verified:
> Add batched telemetry

- src/README.rst
- src/sfctl/custom_cluster.py
> Improve help text on cluster select

- src/setup.py
Fixes # .
- Adding dependency of exact version of sfmergeutility on sfcli so as to prevent any breakages if APIs diverge on future releases.
Verified:
> Adding dependency of exact version of sfmergeutility on sfcli

- src/README.rst
- src/setup.py
Fixes # .
- Bump required sfmergeutility ver to 0.1.6 which contains the security fix to use safe_load instead of yaml.load
-
-
Verified:
> Bump required mergeutil ver to 0.1.6

- src/README.rst
- src/sfctl/apiclient.py
There is a case where sudo permissions may be required when running a command in Linux, but the error message instead says that connection is not found. Improve the error message.
Verified:
> Improve error message

- src/README.rst
- src/setup.py
- src/sfctl/custom_cluster.py
- src/sfctl/tests/version_test.py
Change version numbers for release. Version 7.0.3 will not be released 
Verified:
> Update for 7.1.0 release

- src/README.rst
- src/setup.py
- src/sfctl/custom_cluster.py
> Allow cluster select without explicit endpoint for local testing

- .travis.yml
- pylintrc
- src/setup.py
removes py2 support from the setup.py and the CI tests.
-
-
-
Verified:
> py2 removed.

- .github/workflows/test.yml
- Add step to show tool version from build pipeline
Verified:
> Add support for showing build tools version in pipeline
