microsoft/service-fabric-cli

src/README.rst, src/setup.py
Releasing 1.1.0 version, see release note changes for details
=> Updating for release 1.1.0

LICENSE
=> Updating License

src/README.rst, src/sfctl/custom_app.py, src/sfctl/helps/app.py
=> Fix app upgrade arg naming

.travis.yml, requirements.txt
Adding Coveralls for code coverage during tests
=> Adding coveralls package

CODEOWNERS, pylintrc, src/README.rst, src/setup.py, src/sfctl/commands.py, src/sfctl/custom_app.py, src/sfctl/custom_app_type.py, src/sfctl/custom_chaos.py, src/sfctl/custom_cluster.py, src/sfctl/custom_cluster_upgrade.py, src/sfctl/custom_compose.py, src/sfctl/custom_health.py, src/sfctl/custom_service.py, src/sfctl/helps/app_type.py, src/sfctl/helps/chaos.py, src/sfctl/helps/main.py, src/sfctl/params.py, src/sfctl/tests/app_test.py, src/sfctl/tests/chaos_test.py, src/sfctl/tests/cluster_test.py, src/sfctl/tests/service_test.py
=> Add ChaosContext and ChaosTargetFilter in ChaosParameters and tests in SFCTL

src/README.rst
=> Clarifying some features in the readme

.travis.yml, requirements.txt, src/README.rst, src/setup.py, src/sfctl/auth.py, src/sfctl/custom_app_type.py, src/sfctl/tests/request_generation_test.py
Updating to 5.0.0 release requirements.
Removing custom SDK is part of another PR.
Verifed:
=> 6.2 update

CODEOWNERS, src/sfctl/commands.py, src/sfctl/config.py, src/sfctl/custom_cluster.py, src/sfctl/tests/cluster_test.py, src/sfctl/tests/helpers.py, src/sfctl/tests/request_generation_test.py
Addresses github issue #54 
Verifed:
=> show connection URL

src/README.rst
- Update release notes for 6.0.1 release which updates some help text issues
Verifed:
=> Update release notes for 6.0.1

README.md, src/sfctl/custom_is.py, src/sfctl/custom_property.py, src/sfctl/custom_service.py, src/sfctl/entry.py, src/sfctl/params.py
=> Fix styling in some files to be consistent with pycharm standards

PULL_REQUEST_TEMPLATE.md
- "Verifed" -> "Verified" in PR template
Verified:
=> Resolve PR template typo (verifed -> verified)

README.md
- Update README.md to include license and version badges from PyPi
- Move badges in README.md above opener paragraph, a la other MS repos.
Verified:
=> Add PyPi version + license badges

src/sfctl/custom_cluster.py
- Add detailed comment in code for c_rehash requirement
Verifed:
=> Add detailed comments in custom_cluster

.travis.yml, src/README.rst, src/setup.py, src/sfctl/commands.py, src/sfctl/config.py, src/sfctl/custom_settings.py, src/sfctl/entry.py, src/sfctl/helps/main.py, src/sfctl/helps/settings.py, src/sfctl/send_telemetry_background.py, src/sfctl/telemetry.py, src/sfctl/tests/command_processing_test.py, src/sfctl/tests/custom_help_text_correctness_test.py, src/sfctl/tests/help_text_test.py, src/sfctl/tests/request_generation_test.py, src/sfctl/tests/version_test.py
Add telemetry
- Update knack to the latest version
- Add telemetry. Telemetry is a one try attempt, and failures are not logged.
Verified:
=> Add telemetry

src/README.rst, src/setup.py, src/sfctl/custom_cluster.py, src/sfctl/entry.py, src/sfctl/helps/settings.py, src/sfctl/tests/version_test.py
=> Pause telemetry. Ready for release 7.0.2

src/README.rst, src/setup.py
Fixes # .
-updated readme
-updated msrest version to 0.5.0 because of azure-servicefabric requirement.
-
Verified:
=> updated readme for 8.0.0

pylintrc
=> Allow non top level imports as part of CI

src/README.rst, src/sfctl/custom_service.py, src/sfctl/tests/service_test.py
Fixes # .
-Added ServicePlacementTimeLimit parameter to UpdateService and to CreateService, as part of StatefulServiceDescription
-Added VeryHighMoveCost value for MoveCost.
-Added tests
Verified:
=> New configs

pylintrc
Fixes # .
- Change max line length from 100 -> 120
Verified:
=> Update lint to allow longer max line length

src/sfctl/helps/property.py
=> Fix error in property put help text

src/sfctl/custom_cluster.py
=> Update cluster select doc

cli_license_terms.md
=> Add CLI license terms

src/README.rst, src/setup.py
=> Update knack to version 0.6.3

nose2.cfg
…m sdk.
Fixes # .
-
-
-
Verified:
=> nose2 config for the combination of py2 /py3 files in custom sdk

scripts/check_and_use_custom_sdk.py
=> Add logging for testing set up

src/setup.py
=> Increase Python version allowance until next major version change

src/setup.py, src/sfctl/custom_cluster.py, src/sfctl/tests/cluster_test.py, src/sfctl/tests/version_test.py
Fixes # .
- Updated to use SF 7.1 python sdk.
Verified:
=> version 10 updates for SF 7.1

src/setup.py, src/sfctl/tests/app_test.py, src/sfctl/tests/request_generation_test.py
=> swapped decode for json.dumps

src/README.rst, src/sfctl/helps/main.py
=> updated read me and help text version.

src/README.rst, src/setup.py, src/sfctl/custom_cluster.py, src/sfctl/tests/cluster_test.py, src/sfctl/tests/version_test.py
=> updating versions for 7.2

requirements.txt, src/setup.py
=> switch the locations for the required libs for application upload changes

src/README.rst, src/sfctl/commands.py, src/sfctl/tests/help_text_test.py, src/sfctl/tests/request_generation_test.py
=> loaded partitions in 8.0

src/README.rst, src/sfctl/commands.py, src/sfctl/custom_node.py, src/sfctl/custom_service.py, src/sfctl/helps/node.py, src/sfctl/tests/custom_help_text_correctness_test.py, src/sfctl/tests/help_text_test.py, src/sfctl/tests/request_generation_body_validation.py, src/sfctl/tests/request_generation_test.py, src/sfctl/tests/sample_json/sample_node_tags.txt, src/sfctl/tests/service_test.py
=> Node tagging in 8.0

requirements.txt, src/setup.py
=> Pylint locked

requirements.txt
=> pinned version for astroid

.github/workflows/test.yml
=> changed the test versions.

src/setup.py
=> pinned requests.

requirements.txt, src/README.rst, src/setup.py, src/sfctl/custom_cluster.py, src/sfctl/state.py, src/sfctl/tests/version_test.py
pin requests to 2.27 and updated 1 library along with version checks.
-
-
-
Verified:
=> Pin requests

requirements.txt, src/README.rst, src/setup.py, src/sfctl/custom_cluster.py, src/sfctl/tests/help_text_test.py, src/sfctl/tests/version_test.py
=> update version for release with requests

.github/workflows/test.yml, requirements.txt, scripts/verify.sh, src/setup.py, src/sfctl/custom_app.py, src/sfctl/tests/app_test.py, src/sfctl/tests/help_text_test.py, src/sfctl/tests/version_test.py
=> bump requests
